src/CleanArchitecture.Web/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CleanArchitecture.Web.CustomAttributes;
using Microsoft.AspNetCore.Mvc;


namespace CleanArchitecture.Web.Controllers
{
    [UnAuthorized]
    public class DashboardController : Controller
    {
        [Authorize(Roles.DIRECTOR)]
        public IActionResult DirectorPage()
        {
            ViewBag.UserRole = GetRole();
            ViewBag.Message = "Permission controlled through Authorize Attribute";
            return View("DirectorPage");
        }

        [Authorize(Roles.SUPERVISOR)]
        public IActionResult SupervisorPage()
        {
            ViewBag.UserRole = GetRole();
            ViewBag.Message = "Permission controlled through Authorize Attribute";
            return View("SupervisorPage");
        }

        [Authorize(Roles.ANALYST)]
        public IActionResult AnalystPage()
        {
            ViewBag.UserRole = GetRole();
            ViewBag.Message = "Permission controlled through Authorize Attribute";
            return View("AnalystPage");
        }

        public IActionResult SupervisorAnalystPage()
        {
            ViewBag.UserRole = GetRole();
            ViewBag.Message = "Permission controlled inside action method in-line code";
            if (this.HavePermission(Roles.SUPERVISOR))
                return View("SupervisorPage");

            if (this.HavePermission(Roles.ANALYST))
                return View("AnalystPage");

            return new RedirectResult("~/Dashboard/NoPermission");
        }

        [Authorize(Roles.DIRECTOR, Roles.SUPERVISOR, Roles.ANALYST)]
        public IActionResult PageLevelPermission()
        {
            ViewBag.UserRole = GetRole();
            return View("PageLevelPermission");
        }

        public IActionResult CheckAjaxCalls()
        {
            ViewBag.UserRole = GetRole();
            return View("CheckAjaxCalls");
        }

        public JsonResult AuthenticateAjaxCalls()
        {
            return Json(new { result = "success" });
        }

        [Authorize(Roles.DIRECTOR, Roles.SUPERVISOR)]
        public JsonResult AuthorizeAjaxCalls()
        {
            return Json(new { result = "success" });
        }

        public IActionResult NoPermission()
        {
            ViewBag.UserRole = GetRole();
            return View("NoPermission");
        }

        private string GetRole()
        {
            if (this.HavePermission(Roles.DIRECTOR))
                return " - DIRECTOR";
            if (this.HavePermission(Roles.SUPERVISOR))
                return " - SUPERVISOR";
            if (this.HavePermission(Roles.ANALYST))
                return " - ANALYST";
            return null;
        }
    }
}

src/CleanArchitecture.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using CleanArchitecture.Web.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Http;
using CleanArchitecture.Web.CustomAttributes;
using CleanArchitecture.Core.Entities;
using CleanArchitecture.SharedKernel.Interfaces;
using System;
using CleanArchitecture.Web.Services;
using System.Data.SqlClient;
using System.IO;
using System.Collections.Generic;
using CleanArchitecture.Infrastructure.Data;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using DinkToPdf;
using DinkToPdf.Contracts;
using System.Runtime.Loader;
using System.Reflection;
using Rotativa;
using Rotativa.AspNetCore;
using System.Net;

namespace CleanArchitecture.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IRepository _repository;
        private readonly AppDbContext _dbContext;
        private IConverter _converter;

        public HomeController(AppDbContext dbContext, IRepository _Repository, IConverter converter)
        {
            _dbContext = dbContext;
            _repository = _Repository;
            _converter = converter;
        }

        public IActionResult Index()
        {
            SelfMonitoringModel model = new SelfMonitoringModel();
            var domainName = Request.Host.Value;

            if(domainName.Contains("api.jresources.com"))
            {
                return Redirect("https://play.google.com/store/apps/details?id=com.myjresources");
            }

            #region Site Location
            List<SelectListItem> SiteList = new List<SelectListItem>();
            var siteLocations = _dbContext.SiteLocation.ToList();
            if (siteLocations != null && siteLocations.Count > 0)
            {
                SiteList.Add(new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem()
                {
                    Selected = true,
                    Value = "",
                    Text = "Select Site Location"
                });

                foreach (var item in siteLocations.OrderBy(x => x.nmSite))
                {
                    SiteList.Add(new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem()
                    {
                        Value = item.kdSite,
                        Text = item.nmSite.ToUpper()
                    });
                }
            }
            #endregion

            #region Province
            List<SelectListItem> ProvinceList = new List<SelectListItem>();
            ProvinceList.Add(new SelectListItem()
            {
                Selected = true,
                Value = "",
                Text = "Select Site Province"
            });

            ADOHelper ConnectionCheck = new ADOHelper(AppSettingHelper.HRMSConnectionString);
            string querySite = @"SELECT KdProv, NmProv FROM R_A015 WHERE KdProv != '00' AND stedit <> '2' ORDER BY NmProv";
            SqlDataReader reader = ConnectionCheck.ExecDataReader(querySite, "Year", string.Empty);
            if (reader.HasRows)
            {
                while (reader.Read())
                {
                    ProvinceList.Add(new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem()
                    {
                        Value = reader.GetString(0).Trim(),
                        Text = reader.GetString(1).Trim()
                    });
                }
            }

            #endregion

            ViewBag.DomainName = domainName;
            ViewBag.SiteLocations = SiteList;
            ViewBag.Provinces = ProvinceList;
            ViewData.Model = model;
            return View();
        }

        [HttpPost]
        public IActionResult SelfMonitoring(SelfMonitoringModel model)
        {
            var response = new ResponseModel();
            model.IsFromMobile = false;
            var siteLocation = _dbContext.SiteLocation.FirstOrDefault(x => x.kdSite == model.SiteCode);
            if (siteLocation != null)
            {
                model.SiteCode = siteLocation.kdSite;
                model.SiteName = siteLocation.nmSite.Trim();
            }
            else
            {
                model.SiteCode = string.Empty;
            }

            try
            {
                SelfMonitoringService _service = new SelfMonitoringService(_repository, model);
                response = _service.Save();
            }
            catch (Exception ex)
            {
                response.SetError("Error when saved : " + ex.Message);
            }

            return Ok(response);
        }


        [HttpGet]
        public IActionResult TodoList(string NIKSite)
        {
            SelfMonitoringModel model = new SelfMonitoringModel();
            ViewData.Model = model;


            return View();
        }









        [HttpGet]
        public IActionResult PrivacyPolicy()
        {
            return View();
        }



        public IActionResult Test()
        {
            UserModel objLoggedInUser = new UserModel();
            if (User.Identity.IsAuthenticated)
            {
                var claimsIndentity = HttpContext.User.Identity as ClaimsIdentity;
                var userClaims = claimsIndentity.Claims;

                if (HttpContext.User.Identity.IsAuthenticated)
                {
                    foreach (var claim in userClaims)
                    {
                        var cType = claim.Type;
                        var cValue = claim.Value;
                        switch (cType)
                        {
                            case "UserId":
                                objLoggedInUser.Id = cValue;
                                break;
                            case "Name":
                                objLoggedInUser.FullName = cValue;
                                break;
                            case "Email":
                                objLoggedInUser.Email = cValue;
                                break;
                            case "Role":
                                objLoggedInUser.Role = cValue;
                                break;
                        }
                    }
                }
            }

            return View("Test", objLoggedInUser);
        }

        public IActionResult Employee()
        {
            return View();
        }

        public IActionResult Attendance()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }

        public IActionResult Logoff()
        {
            HttpContext.Session.Clear();
            return Redirect("~/Home/Index");
        }

        public JsonResult EndSession()
        {
            HttpContext.Session.Clear();
            return Json(new { result = "success" });
        }
        private string GetRole()
        {
            if (this.HavePermission(Roles.DIRECTOR))
                return " - DIRECTOR";
            if (this.HavePermission(Roles.SUPERVISOR))
                return " - SUPERVISOR";
            if (this.HavePermission(Roles.ANALYST))
                return " - ANALYST";
            return null;
        }

        public class CustomAssemblyLoadContext : AssemblyLoadContext
        {
            public IntPtr LoadUnmanagedLibrary(string absolutePath)
            {
                return LoadUnmanagedDll(absolutePath);
            }
            protected override IntPtr LoadUnmanagedDll(string unmanagedDllName)
            {
                return LoadUnmanagedDllFromPath(unmanagedDllName);
            }
            protected override Assembly Load(AssemblyName assemblyName)
            {
                throw new NotImplementedException();
            }
        }

        [HttpGet]
        public IActionResult DocumentView()
        {

            return View();
        }


        [HttpGet]
        public IActionResult Download()
        {
            //string ddllibwkhtmltox = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "files", "libwkhtmltox.dll");
            //new CustomAssemblyLoadContext().LoadUnmanagedLibrary(ddllibwkhtmltox);

            //var globalSettings = new GlobalSettings
            //{
            //    ColorMode = ColorMode.Color,
            //    Orientation = Orientation.Portrait,
            //    PaperSize = PaperKind.A4,
            //    Margins = new MarginSettings { Top = 10 },
            //    DocumentTitle = "PDF Report",
            //    Out = Path.Combine(
            //        Directory.GetCurrentDirectory(), "wwwroot", "files", "test.pdf"
            //    )
            //};

            //var objectSettings = new ObjectSettings
            //{
            //    PagesCount = true,
            //    Page = "http://localhost:3835/Home/DocumentView",
            //    //HtmlContent = "<b>TEST TEST TEST<b>",
            //    WebSettings = { DefaultEncoding = "utf-8", UserStyleSheet = Path.Combine(Directory.GetCurrentDirectory(), "assets", "styles.css") },
            //    HeaderSettings = { FontName = "Arial", FontSize = 9, Right = "Page [page] of [toPage]", Line = true },
            //    FooterSettings = { FontName = "Arial", FontSize = 9, Line = true, Center = "Report Footer" }
            //};

            //var pdf = new HtmlToPdfDocument()
            //{
            //    GlobalSettings = globalSettings,
            //    Objects = { objectSettings }
            //};

            //_converter.Convert(pdf);
            //return Ok("Successfully created PDF document.");
            return new ViewAsPdf("DocumentView");
        }

        public IActionResult DownloadSKPM(String NIKSite)
        {
            return Redirect("/Reporting?NIKSite=" + NIKSite);
        }

        public IActionResult DownloadSKPMFromServer(String NIKSite)
        {
            //return Redirect("/Reporting?NIKSite=" + NIKSite);
            string uriDownload = AppSettingHelper.ReportingURL + NIKSite;
            var path = Path.Combine(

src/CleanArchitecture.Web/Controllers/ToDoController.cs
using CleanArchitecture.Core.Entities;
using CleanArchitecture.SharedKernel.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace CleanArchitecture.Web.Controllers
{
    public class ToDoController : Controller
    {
        private readonly IRepository _todoRepository;

        public ToDoController(IRepository todoRepository)
        {
            _todoRepository = todoRepository;
        }

        public IActionResult Index()
        {
            var items = _todoRepository.List<ToDoItem>();
            return View(items);
        }

        public IActionResult Populate()
        {
            int recordsAdded = PopulateDatabase();
            return Ok(recordsAdded);
        }

        public int PopulateDatabase()
        {
            if (_todoRepository.List<ToDoItem>().Any()) return 0;
            _todoRepository.Add(new ToDoItem()
            {
                Title = "Get Sample Working",
                Description = "Try to get the sample to build."
            });
            _todoRepository.Add(new ToDoItem()
            {
                Title = "Review Solution",
                Description = "Review the different projects in the solution and how they relate to one another."
            });
            _todoRepository.Add(new ToDoItem()
            {
                Title = "Run and Review Tests",
                Description = "Make sure all the tests run and review what they are doing."
            });
            return _todoRepository.List<ToDoItem>().Count;
        }
    }
}

src/CleanArchitecture.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

src/CleanArchitecture.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/CleanArchitecture.Web/Views/Home/DocumentView.cshtml
@{
    Layout = null;
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Mobile Attendance</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700|Roboto:300,400,500,600,700">
    <!--begin::Page Vendors Styles(used by this page) -->
    <link href="~/assets/plugins/custom/fullcalendar/fullcalendar.bundle.css" rel="stylesheet" type="text/css" />

    <!--end::Page Vendors Styles -->
    <!--begin::Global Theme Styles(used by all pages) -->
    <link href="~/assets/plugins/global/plugins.bundle.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/style.bundle.css" rel="stylesheet" type="text/css" />

    <!--end::Global Theme Styles -->
    <!--begin::Layout Skins(used by all pages) -->
    <link href="~/assets/css/skins/header/base/light.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/skins/header/menu/light.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/skins/brand/dark.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/skins/aside/dark.css" rel="stylesheet" type="text/css" />


    <style>
#invoice{
    padding: 30px;
}

.invoice {
    position: relative;
    background-color: #FFF;
    min-height: 680px;
    padding: 15px
}

.invoice header {
    padding: 10px 0;
    margin-bottom: 20px;
    border-bottom: 1px solid #3989c6
}

.invoice .company-details {
    text-align: right
}

.invoice .company-details .name {
    margin-top: 0;
    margin-bottom: 0
}

.invoice .contacts {
    margin-bottom: 20px
}

.invoice .invoice-to {
    text-align: left
}

.invoice .invoice-to .to {
    margin-top: 0;
    margin-bottom: 0
}

.invoice .invoice-details {
    text-align: right
}

.invoice .invoice-details .invoice-id {
    margin-top: 0;
    color: #3989c6
}

.invoice main {
    padding-bottom: 50px
}

.invoice main .thanks {
    margin-top: -100px;
    font-size: 2em;
    margin-bottom: 50px
}

.invoice main .notices {
    padding-left: 6px;
    border-left: 6px solid #3989c6
}

.invoice main .notices .notice {
    font-size: 1.2em
}

.invoice table {
    width: 100%;
    border-collapse: collapse;
    border-spacing: 0;
    margin-bottom: 20px
}

.invoice table td,.invoice table th {
    padding: 15px;
}

.invoice table th {
    white-space: nowrap;
    font-weight: 400;
    font-size: 16px
}

.invoice table td h3 {
    margin: 0;
    font-weight: 400;
    color: #3989c6;
    font-size: 1.2em
}

.invoice table .qty,.invoice table .total,.invoice table .unit {
    text-align: right;
    font-size: 1.2em
}

.invoice table .no {
    color: #fff;
    font-size: 1.6em;
    background: #3989c6
}

.invoice table .unit {
    background: #ddd
}

.invoice table .total {
    background: #3989c6;
    color: #fff
}


.invoice table tfoot td {
    background: 0 0;
    border-bottom: none;
    white-space: nowrap;
    text-align: right;
    padding: 10px 20px;
    font-size: 1.2em;
    border-top: 1px solid #aaa
}

.invoice table tfoot tr:first-child td {
    border-top: none
}

.invoice table tfoot tr:last-child td {
    color: #3989c6;
    font-size: 1.4em;
    border-top: 1px solid #3989c6
}

.invoice table tfoot tr td:first-child {
    border: none
}

.invoice footer {
    width: 100%;
    text-align: center;
    color: #777;
    border-top: 1px solid #aaa;
    padding: 8px 0
}

@@media print {
    .invoice {
        font-size: 11px!important;
        overflow: hidden!important
    }

    .invoice footer {
        position: absolute;
        bottom: 10px;
        page-break-after: always
    }

    .invoice>div:last-child {
        page-break-before: always
    }
}
    </style>

    
</head>
<body class="">
    <!-- begin:: Page -->

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    <!--Author      : @@arboshiki-->
    <div id="invoice">


        <div class="invoice overflow-auto">
            <div style="min-width: 600px">
                <header>
                    <div class="row">
                        <div class="col">
                            <img src="~/assets/media/logos/logo-280.png" data-holder-rendered="true" />
                        </div>
                        <div class="col company-details">
                            <h2 class="name">
                                Equity Tower, 48th Floor, SCBD Lot.9
                            </h2>
                            <div>Jl. Jenderal Sudirman, Kav.52-53</div>
                            <div>Jakarta, 12190, Indonesia</div>
                            <div>+62 (21) 515-3335</div>
                            <div>corpsec@@jresources.com</div>
                        </div>
                    </div>
                </header>
                <main>
                    <h2 class="to" style="text-align: center;">SURAT KETERANGAN KERJA</h2>
                    <h4 style="text-align: center; margin-bottom: 10px;">No : SKK/HRD-DEP/JRBM/1421/042020</h4>

                    <div class="notices" style="border-left: 0; padding-left: 0;">
                        <div class="notice">
                            Yang bertanda tangan dibawah ini bertindak dan atas nama Human Resource Department Manager PT J
                            RESOURCES BOLAANG MONGONDOW, yang berkedudukan di Jl. Kol. Sugiono No. 24, Kotabangun ,
                            Kotamobagu Timur ,Sulawesi Utara 95712 -Indonesia. Telp.: +62 (434) 21018 Fax.: +62 (434) 22965 / 23387,
                            menerangkan dengan sebenarnya bahwa :
                        </div>
                    </div>

                    <br />
                    <br />

                    <div class="row justify-content-md-center">

                        <div class="col-md-auto" style="padding: 10px 100px;">

                            <table class="table table-bordered" border="0" cellspacing="0" cellpadding="0">
                                <tbody>
                                    <tr>
                                        <td style="width: 200px;">Nama</td>
                                        <td>:</td>
                                        <td>EDI HARTANTO</td>
                                    </tr>
                                    <tr>
                                        <td>NIK</td>
                                        <td>:</td>
                                        <td>AK-1369</td>
                                    </tr>
                                    <tr>
                                        <td>Tempat, Tanggal Lahir</td>
                                        <td>:</td>
                                        <td>MAGELANG, 26/Mar/1993</td>
                                    </tr>
                                    <tr>
                                        <td>Alamat</td>
                                        <td>:</td>
                                        <td>
                                            DSN GLAGAH 2 RT. 03 RW. 04,
                                            DESA BANJARNEGORO, KEC.
                                            MERTOYUDAN Magelang Jawa
                                            Tengah
                                        </td>
                                    </tr>
                                </tbody>
                            </table>

                        </div>

                    </div>


                    <div class="notices" style="border-left: 0; padding-left: 0;">
                        <div class="notice">
                            Telah bekerja di perusahaan kami sejak tanggal 03/Nov/2014 dengan jabatan terakhir sebagai Mechanic -
                            Wheel Equipment Maintenance. Karyawan tersebut diatas telah menjalankan pengawasan kesehatan yang
                            ketat dari tim pencegahan penyebaran COVID-19 perusahaan selama 14 hari terakhir sejak tanggal
                            04/Apr/2020 s/d 18/Apr/2020 dengan hasil sebagai berikut
                        </div>
                    </div>

                    <br />

                    <div class="notices" style="border-left: 0; padding-left: 0;">
                        <div class="notice">
                            Demikian surat keterangan ini diberikan untuk dapat digunakan sebagaimana mestinya.
                        </div>
                    </div>





                </main>
                <footer>
                    Invoice was created on a computer and is valid without the signature and seal.
                </footer>
            </div>
            <!--DO NOT DELETE THIS div. IT is responsible for showing footer always at the bottom-->
            <div></div>
        </div>
    </div>



    <!-- end:: Page -->
    <!--begin::Global Theme Bundle(used by all pages) -->
    <script src="~/assets/plugins/global/plugins.bundle.js" type="text/javascript"></script>
    <script src="~/assets/js/scripts.bundle.js" type="text/javascript"></script>
    <!--end::Global Theme Bundle -->





</body>
</html>

src/CleanArchitecture.Web/Views/Home/Test.cshtml
@model CleanArchitecture.Web.Models.UserModel

@{
    ViewData["Title"] = "Clean DDD Architecture Sample";
}

<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">



    <!--Begin::Dashboard 1-->

    @if (User.Identity.IsAuthenticated)
    {
        <div class="row">
            You are Logged in as <span style="font-size:large;color:forestgreen;">@User.Identity.Name</span>
        </div>
        <div style="padding-top:30px;"></div>
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-3">
                <div><b>Your Claim Values:</b></div>
                <div style="padding-top:10px;">
                    <div>
                        <table>
                            <tr>
                                <td style="width:30%;">User ID</td>
                                <td style="width:50%;"><label>@Model.Id</label></td>
                            </tr>
                            <tr>
                                <td>Email ID</td>
                                <td><label>@Model.Email</label></td>
                            </tr>
                            <tr>
                                <td>Access Level</td>
                                <td><label style="color:forestgreen">@Model.Role</label></td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-9 col-md-9 col-sm-9">
                <div><b>Links to check your permissions</b></div>
                <div style="padding-top:20px;"></div>
                <ul>
                    <li>@Html.ActionLink("Go to Director Page", "DirectorPage", "Dashboard")</li>
                    <li style="padding-top:5px;">@Html.ActionLink("Go to Supervisor Page", "SupervisorPage", "Dashboard")</li>
                    <li style="padding-top:5px;">@Html.ActionLink("Go to Analyst Page", "AnalystPage", "Dashboard")</li>
                    <li style="padding-top:5px;">@Html.ActionLink("See how user permissions controlled inside action method In-line code - Only for Supervisor & Analyst", "SupervisorAnalystPage", "Dashboard")</li>
                    <li style="padding-top:5px;">@Html.ActionLink("See how view page level permission works (Login in as Analyst JBlack@email.com who do not have WRITE permission)", "PageLevelPermission", "Dashboard")</li>
                    <li style="padding-top:5px;">@Html.ActionLink("See how Authentication & Authorization handled for Ajax Calls", "CheckAjaxCalls", "Dashboard")</li>
                </ul>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <h2>To Do Items (MVC)</h2>
                <ul>
                    <li><a asp-area="" asp-controller="ToDo" asp-action="Populate">Load Sample To Do Items</a> (API call returning just a number)</li>
                    <li><a asp-area="" asp-controller="ToDo" asp-action="Index">List To Do Items</a></li>
                    <li><a href="/swagger">API Documentation (Swagger)</a></li>
                </ul>
                <h2>To Do Items (Razor Pages)</h2>
                <ul>
                    <li><a asp-page="/ToDoRazorPage/Populate">Load Sample To Do Items</a></li>
                    <li><a asp-page="/ToDoRazorPage/Index">List To Do Items</a></li>
                </ul>
            </div>
            <div class="col-md-6">
                <h2>About the Author</h2>
                <ul>
                    <li><a href="https://ardalis.com">Blog - Ardalis.com</a></li>
                    <li><a href="https://twitter.com/ardalis">Twitter - @@ardalis</a></li>
                    <li><a href="https://github.com/ardalis">GitHub</a></li>
                </ul>
            </div>
        </div>
    }
    else
    {
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-4">
                <div>
                    @using (Html.BeginForm("LoginUser", "Home", FormMethod.Post, new { role = "form" }))
                    {
                        <div>
                            @Html.AntiForgeryToken()
                            <div>
                                <label>User ID</label><br />
                            </div>
                            <div>
                                @Html.TextBoxFor(m => m.Id, new { @class = "form-control txtbox" })
                            </div>
                            <div style="padding-top:20px;"></div>
                            <div>
                                <label>Password</label><br />
                            </div>
                            <div>
                                @Html.Password("Password", new { @class = "form-control txtbox" })
                            </div>
                        </div>
                        <div style="padding-left:35%;width:40%;">
                            <div style="padding-top:20px;">
                                <input class="btn btn-primary btn-lg rph-login-button" type="submit" value="Login" />
                            </div>
                        </div>
                    }
                </div>
            </div>
            <div class="col-lg-8 col-md-8 col-sm-8">
                <div style="padding-left:50px;">
                    <div><b>Please login with any of the below User ID, Password is <span style="color:forestgreen;font-size:large;">test</span> for all Users</b></div>
                    <div style="padding-top:10px;">
                        <ul style="list-style: none;">
                            <li>jsmith@email.com  -  Director</li>
                            <li>srob@email.com  -  Supervisor</li>
                            <li>dwill@email.com  -  Analyst</li>
                            <li>JBlack@email.com  -  Analyst with 'No Write' access</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    }
</div>